### ISSUE TITLE
Showing Values in the Apple Home app?

### ISSUE THREAD

**Issue by jamie-2bit** [AllMightySauron/homebride-solaxcloud-api#1]
Does this show usage statistics nativly in the Apple Home app? All I can see is outlets "on/off". Can it use LUX level for example to display Kwh from the inverter?

**Comment by troygNZ** [comment]
To evaluate if you like this as a feature, and you think it’s worthwhile adding this - this is what it looks like (including me showing individual string feeds, and non weighted average raw values.

![CEC21CDA-72AD-4C9A-8D6A-603B1EF75FF6](https://user-images.githubusercontent.com/6609870/148343335-b98185cb-e5ca-4ae0-bd31-840fa80fb12f.jpeg)

Screenshot serving from my non cloud version of a Solax Homebridge plugin - https://github.com/troygNZ/homebridge-solax

**Comment by AllMightySauron** [comment]
> Does this show usage statistics nativly in Homebridge? All I can see if on/off. Can it use LUX level for example to display Kwh from the inverter?

Hi @jamie-2bit , 

Yes, the plugin provides usage statistics. Take a look at my latest data below :)

![Screenshot 2022-01-06 at 08 48 24](https://user-images.githubusercontent.com/72256753/148355714-2c6cecd0-ff5e-4557-bb94-13ddf0fc6f55.png)

I'm guessing you're using the standard Apple Home app if you can only see on/off characteristics for outlets. Please note that you need to install the [Eve for Homekit](https://apps.apple.com/us/app/eve-for-homekit/id917695792) or [Controller for HomeKit](https://apps.apple.com/us/app/controller-for-homekit/id1198176727) app from the App store.

The reason why i'm using these non-standard characteristics is due to the fact that I want to maintain history and see the graphs provided by Eve out-of-the-box.

Regards

**Comment by AllMightySauron** [comment]
> To evaluate if you like this as a feature, and you think it’s worthwhile adding this - this is what it looks like (including me showing individual string feeds, and non weighted average raw values.
> 
> ![CEC21CDA-72AD-4C9A-8D6A-603B1EF75FF6](https://user-images.githubusercontent.com/6609870/148343335-b98185cb-e5ca-4ae0-bd31-840fa80fb12f.jpeg)
> 
> Screenshot serving from my non cloud version of a Solax Homebridge plugin - https://github.com/troygNZ/homebridge-solax

Hi @troygNZ , I took a look at your plugin before creating this new one.  :wink:

Adding new light accessories with Lux characteristics could overcome the need for using non-standard characteristics for accessories (we could even have both, for that matter :smile:). However, you would lose the ability to oversee charts and history that is offered by the standard Eve history functionality.

This is what I get in Eve, which is basically the same information from your screenshot:

![Screenshot 2022-01-06 at 08 59 17](https://user-images.githubusercontent.com/72256753/148357335-2914b6a2-cbc5-443d-9ecd-1b3fa84e9291.png)



Hope it helps clarifying the issue.

**Comment by jamie-2bit** [comment]
Thanks @AllMightySauron and @troygNZ 

Yes, I'm using the native Apple Home app. I don't personally have the need to see historical data as I can get this in the Solax app itself. I just need real time (5min) data in order to run automations.

Sounds like you two need to combine forces and have the best of both your plugins. Have Solax values showing as LUX levels in the native Apple Home app and have it pulling the values via the Solax Cloud API. 

( @troygNZ turns out I can't use your plugin as my inverter has newer firmware and doesn't support the direct API call)

**Comment by AllMightySauron** [comment]
> Thanks @AllMightySauron and @troygNZ
> 
> Yes, I'm using the native Apple Home app. I don't personally have the need to see historical data as I can get this in the Solax app itself. I just need real time (5min) data in order to run automations.
> 
> Sounds like you two need to combine forces and have the best of both your plugins. Have Solax values showing as LUX levels in the native Apple Home app and have it pulling the values via the Solax Cloud API.
> 
> ( @troygNZ turns out I can't use your plugin as my inverter has newer firmware and doesn't support the direct API call)

@jamie-2bit , I reckon I can do both. 

What if I add a parameter like, let's say 'Home App Only', and if you set it to true it only creates the Lights with Lux? Would that do the trick?

**Comment by jamie-2bit** [comment]
> > Thanks @AllMightySauron and @troygNZ
> > Yes, I'm using the native Apple Home app. I don't personally have the need to see historical data as I can get this in the Solax app itself. I just need real time (5min) data in order to run automations.
> > Sounds like you two need to combine forces and have the best of both your plugins. Have Solax values showing as LUX levels in the native Apple Home app and have it pulling the values via the Solax Cloud API.
> > ( @troygNZ turns out I can't use your plugin as my inverter has newer firmware and doesn't support the direct API call)
> 
> @jamie-2bit , I reckon I can do both.
> 
> What if I add a parameter like, let's say 'Home App Only', and if you set it to true it only creates the Lights with Lux? Would that do the trick?

I think that would be an amazing feature and would help a lot of people with the same use-case as myself! Is it tough to implement?

**Comment by troygNZ** [comment]
Feel free to steal my code that surfaces the data as light sensors. It’ll be helpful for those with the cloud version of solax. You may find it useful to provide moving averages on alerts etc, so take fluctuations out when cloud temporarily goes over etc. I have those implemented too. Alternatively, if I can find time I can fork and do a PR back. Disclaimer, I’m not a seasoned NodeJS + TS dev.

**Comment by AllMightySauron** [comment]
@troygNZ , @jamie-2bit 

Just to let you know I already have a new version up and running with the option to use ambient light sensors for power. I'll be testing it out over the next couple of days and then publish a beta version for you to test.

Cheers

**Comment by jamie-2bit** [comment]
> @troygNZ , @jamie-2bit
> 
> Just to let you know I already have a new version up and running with the option to use ambient light sensors for power. I'll be testing it out over the next couple of days and then publish a beta version for you to test.
> 
> Cheers

How's it been working so far @AllMightySauron ?

**Comment by AllMightySauron** [comment]
![image](https://user-images.githubusercontent.com/72256753/150115789-7ace5f22-5827-4377-8fd2-bf2a5f0b7645.png)

Looking good 😄

**Comment by AllMightySauron** [comment]
@jamie-2bit , I have just made the beta version available. You can install it by using `npm -g install homebridge-solaxcloud-api@beta`. 

Let me know how it goes...

**Comment by jamie-2bit** [comment]
> Let me know how it goes...

Will do, I'll need to wait until the morning for the inverter to kick back in so I'll let you know then. Cheers!

**Comment by AllMightySauron** [comment]
> > Let me know how it goes...
> 
> Will do, I'll need to wait until the morning for the inverter to kick back in so I'll let you know then. Cheers!

just to let you know, I have added exponential moving average support on 2.0.2-beta.0

**Comment by AllMightySauron** [comment]
> > > Let me know how it goes...
> > 
> > 
> > Will do, I'll need to wait until the morning for the inverter to kick back in so I'll let you know then. Cheers!
> 
> just to let you know, I have added exponential moving average support on 2.0.2-beta.0

@jamie-2bit, any news?

**Comment by jamie-2bit** [comment]
> > > > Let me know how it goes...
> > > 
> > > 
> > > Will do, I'll need to wait until the morning for the inverter to kick back in so I'll let you know then. Cheers!
> > 
> > 
> > just to let you know, I have added exponential moving average support on 2.0.2-beta.0
> 
> @jamie-2bit, any news?

Tested it today. It’s working perfectly so far on 2.0.2. Good job!!

**Comment by AllMightySauron** [comment]
> > > > > Let me know how it goes...
> > > > 
> > > > 
> > > > Will do, I'll need to wait until the morning for the inverter to kick back in so I'll let you know then. Cheers!
> > > 
> > > 
> > > just to let you know, I have added exponential moving average support on 2.0.2-beta.0
> > 
> > 
> > @jamie-2bit, any news?
> 
> Tested it today. It’s working perfectly so far on 2.0.2. Good job!!

Great! I'll move it into production :smile:

**Comment by troygNZ** [comment]
Great work. I only have the non cloud variant, but great stuff! Cool to see your repo progressing nicely!
