### ISSUE TITLE
Plugin fails after some time 

### ISSUE THREAD

**Issue by JanHios** [AllMightySauron/homebride-solaxcloud-api#4]
**Describe The Bug:**
the plug-in stops working from time to time with the following error in the log. Only a Homebridge restart helps. Other plug-ins continue to work in parallel. Only the Solax plug-in stops working
![692EF3B1-FF14-4FAC-89F2-ADAF39C04DFC](https://user-images.githubusercontent.com/102536190/179926124-d1cd757f-59ff-4194-9531-58ca23559c99.jpeg)

**To Reproduce:**
difficult to say - it suddenly started. 

**Expected behavior:**
work normally 

**Logs:**
See screenshot above

**Comment by AllMightySauron** [comment]
Hi Jan, I'm on it. I do not get any errors, but I am running the plugin with just 1 inverter :smile: ...

**Comment by AllMightySauron** [comment]
@JanHios , can you please test out version [2.1.8](https://github.com/AllMightySauron/homebride-solaxcloud-api/releases/tag/2.1.8)?

I have simplified the data pooling sleep mechanism. I hope this solves it...

**Comment by JanHios** [comment]
I have installed it right after your message and until now it works fine. Let me test it for some more days, but of you don’t hear anything from me until end of next week it is working fine.
