### ISSUE TITLE
Battery unsupported

### ISSUE THREAD

**Issue by s1rbruce** [AllMightySauron/homebride-solaxcloud-api#7]
Hi, thank you for amazing plugin, I wanna ask you about battery, which is showing unsuporrted state. But when I installed for first time, it worked for few minutes, but shows that is not supported in homekit.

Am I doing something wrong? Thanks

**Comment by AllMightySauron** [comment]
Hi, did you set the "Battery installed?" in configuration to **true** for your inverter?

![image](https://github.com/AllMightySauron/homebride-solaxcloud-api/assets/72256753/24e63eda-4949-437d-a4a7-509bc55f2f71)

**Comment by s1rbruce** [comment]
Yes, and battery showing as unsuported

**Comment by s1rbruce** [comment]
![image](https://github.com/AllMightySauron/homebride-solaxcloud-api/assets/69530212/4b15f513-8403-4f33-82c8-b425d9e28e15)![image](https://github.com/AllMightySauron/homebride-solaxcloud-api/assets/69530212/ab3a0f03-4517-4527-802d-fea74d5f4234)

**Comment by AllMightySauron** [comment]
Sorry, can you point to the unsupported part on the above pictures? :smile:

**Comment by s1rbruce** [comment]
Yes, sorry :-D

I think thats why it missing at top bar, after reseting server it apears for few minutes then dissapear

![image](https://github.com/AllMightySauron/homebride-solaxcloud-api/assets/69530212/97ef6b51-72ac-484a-bead-d9a77c4b51b2)

![image](https://github.com/AllMightySauron/homebride-solaxcloud-api/assets/69530212/3a9fc171-abe0-4d26-a894-ac27c8ed4580)


![image](https://github.com/AllMightySauron/homebride-solaxcloud-api/assets/69530212/b4ef16e1-751b-4426-a0a3-b6b304a4477f)

**Comment by AllMightySauron** [comment]
That is weird...

Even though mine says "Unsupported" at the room level, when I look at the accessory details, it flashes "This accessory is not currently supported by the Home app." for a brief moment while loading and then updates to this:

![Screenshot 2024-03-14 at 13 59 08](https://github.com/AllMightySauron/homebride-solaxcloud-api/assets/72256753/69e372d9-f851-479a-9d4e-62570d7a06ab)

Is the data displayed in terms of battery % correct?

Also, what versions are you using for both homebridge and iOS?

**Comment by s1rbruce** [comment]
% of battery showing true data, so i dont know what should be wrong

iOS 17.4 and homebridge v4.55.1

**Comment by AllMightySauron** [comment]
What plugin version are you using?

Latest is 2.3.0.

**Comment by s1rbruce** [comment]
2.3.0 keeping it up to date
