### ISSUE TITLE
TokenID can have more than 23 characters

### ISSUE THREAD

**Issue by fabian4343** [AllMightySauron/homebride-solaxcloud-api#8]
**Describe The Bug:**
The TokenID field in the setup allows only 23 characters. But it can also have 24 oder more. In my case it´s 24 characters.

**To Reproduce:**
Entering a TokenID with more than 23 characters in setup.

**Expected behavior:**
Being able to input more than 23 characters, at least 24.

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

![Bildschirmfoto 2024-04-01 um 16 48 02](https://github.com/AllMightySauron/homebride-solaxcloud-api/assets/165667683/c778e604-6880-4f7b-b1af-349e540dcf0e)

**Environment:**

* **Plugin Version**: 2.3.0
* **Homebridge Version**: current, 1.1.6
* **Node.js Version**: v18.19.0
* **NPM Version**: 
* **Operating System**:

**Comment by AllMightySauron** [comment]
fixed in 2.3.1
